apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "parasol-store-build.name" . }}-trigger-pipeline
  labels:
    {{- include "parasol-store-build.labels" . | nindent 4 }}
data:
  trigger-pipeline.yaml: |
    apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: {{ include "parasol-store-build.name" . }}-init-build-
      labels:
        {{- include "parasol-store-build.labels" . | nindent 8 }}
        backstage.io/kubernetes-id: {{ .Values.backstage.id }}
    spec:
      params:
        - name: source-repo
          value: https://{{ .Values.gitlab.host }}/{{ .Values.gitlab.group }}/{{ .Values.gitlab.project }}.git
        - name: source-branch
          value: {{ .Values.gitlab.branch }}
        - name: output-image
          value: {{ include "image.url" . }}
        - name: output-image-tag
          value: {{ .Values.image.tag }}
        - name: username
          value: 'unknown'
        - name: email
          value: 'unknown@acme.com'
          ##Note: The first run, triggered by the job will not have
          ##      commit verification, therefore not needed (and not available anyway)
      pipelineRef:
        name: {{ include "parasol-store-build.name" . }}-build
      taskRunTemplate:
        serviceAccountName: pipeline
      timeouts:
        pipeline: 1h0m0s
      workspaces:
        - name: source-folder
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - emptyDir: {}
          name: maven-settings
        - name: docker-config
          emptyDir: {}
        - name: tas-environment
          emptyDir: {}
