apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: setup-environment
spec:
  results:
    - name: tas-env-vars
      description: Environment variables as base64 encoded string
  workspaces:
    - name: environment
      description: Workspace to store environment files
  steps:
  - name: cosign-environment
    image: registry.redhat.io/openshift4/ose-cli:latest
    workingDir: $(workspaces.environment.path)
    script: |
      #!/bin/bash
      set -e
      
      # The service account token is automatically mounted
      echo "Current user:"
      oc whoami
      
      /scripts/init-tas.sh

      # Verify that the environment file was created
      if [ -f tas-env.sh ]; then
        base64 -w 0 tas-env.sh > $(results.tas-env-vars.path)
        echo "Environment variables encoded and saved to result"
      else
        echo "ERROR: Environment file was not created"
        exit 1
      fi
      
    volumeMounts:
      - name: script-volume
        mountPath: /scripts
        readOnly: true
  volumes:
    - name: script-volume
      configMap:
        name: tas-init-script
        defaultMode: 0755  # Make the script executable