---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ include "parasol-store-build.name" . }}-build
spec:
  params:
    - name: git-revision
      description: The git revision
      default: {{ .Values.gitlab.branch }}
    - name: git-repo-url
      description: The repo url
    - name: output-image
      description: reference of the image that will get created
      default: {{ include "image.url" . }}
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: {{ include "parasol-store-build.name" . }}-build-$(uid)
        labels:
          backstage.io/kubernetes-id: {{ .Values.backstage.id }}
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: $(tt.params.git-revision)
          - name: output-image
            value: $(tt.params.output-image)
          - name: component-id
            value: {{ include "parasol-store-build.name" . }}
        pipelineRef:
          name: {{ include "parasol-store-build.name" . }}-build
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: source-folder
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: maven-settings
            emptydir: {}
          - name: docker-config
            emptyDir: {}
